import {RECEIVING, type Product} from './receiving-service.ts';
import {barcodeAliases, barcodeKey, gid, money, optionalStorePrice, ReceivingError, scanBarcode, stableJson, text, validBarcode, validation} from './receiving-validation.ts';
import {directGraphQL, type GraphQL} from './shopify-receiving-adapter.ts';
import {RECEIVING_CATALOG_GAMES} from './receiving-catalog.ts';

export type CheckoutInput = {requestId: string; productId: string; variantId: string; sku: string; barcode: string; storePrice?: string};
export type CheckoutResult = {ok: true; product: Product; publicationId: string} | {
  ok: false; error: {code: string; message: string; retryable: boolean; committedPossible: boolean};
};
type Json = Record<string, any>;
type PriceAttempt = {version: 1; fingerprint: string; request: CheckoutInput; before: string; phase: 'pending' | 'applied'};
type Marker = {value: string; compareDigest: string};
type Current = {product: Product; node: Json; parent: Json; marker: Marker | null; activeMarker: Marker | null};

function fail(code: string, message: string, retryable = false): never {
  throw new ReceivingError(code, message, retryable, false);
}
function check(payload: Json, action: string) {
  if (!payload) fail('CHECKOUT_UNCERTAIN', `${action} could not be confirmed. Retry the same checkout request.`, true);
  if (payload.userErrors?.length) fail('SHOPIFY_REJECTED', `${action}: ${payload.userErrors.map((error: Json) => error.message).join('; ')}`);
}
function normalize(input: CheckoutInput): CheckoutInput {
  if (!input || typeof input !== 'object') validation('Select the sealed Shopify product first.');
  const requestId = text(input.requestId, 'Checkout request ID', 48, true);
  if (!/^[a-z0-9][a-z0-9-]{15,47}$/.test(requestId)) validation('Use the checkout request ID generated by this receiver.');
  const storePrice = optionalStorePrice(input.storePrice);
  if (storePrice !== undefined && Number(storePrice) <= 0) validation('Store price must be greater than 0.00 to make the product available at checkout.');
  return {requestId, productId: gid(input.productId, 'Product'), variantId: gid(input.variantId, 'ProductVariant'),
    sku: text(input.sku, 'SKU', 80, true), barcode: scanBarcode(input.barcode), ...(storePrice !== undefined ? {storePrice} : {})};
}
const channelTypes = {appChannels: 'APP', marketChannels: 'MARKET', companyChannels: 'COMPANY_LOCATION', noCatalogChannels: 'NONE'};
const memberships = Object.entries(channelTypes).map(([alias, catalogType]) => `${alias}: resourcePublicationsV2(first: 100, onlyPublished: false, catalogType: ${catalogType}) { nodes { publication { id } } pageInfo { hasNextPage } }`).join('\n');

/** Explicit POS availability repair. It never receives stock or modifies receipts. */
export class CheckoutService {
  readonly graphql: GraphQL;
  constructor(graphql: GraphQL = directGraphQL) { this.graphql = graphql; }

  private async publication(request: CheckoutInput): Promise<string> {
    const connection = await this.graphql(`query ReceivingCheckoutScopes {
      currentAppInstallation { accessScopes { handle } }
      shop { receiving: metafield(namespace: "${RECEIVING.namespace}", key: "${RECEIVING.stateKey}") { value } }
    }`);
    const scopes = new Set(connection.currentAppInstallation?.accessScopes?.map((scope: Json) => scope.handle));
    const missing = ['write_products', 'write_publications'].filter(scope => !scopes.has(scope));
    if (missing.length) fail('CHECKOUT_PERMISSION_REQUIRED', `The Shopify app needs ${missing.join(' and ')} permission. Ask the owner to approve the updated app permissions.`);
    if (connection.shop?.receiving) {
      let journal: Json;
      try { journal = JSON.parse(connection.shop.receiving.value); } catch { fail('CHECKOUT_RECEIVING_REVIEW', 'The receiving journal needs owner review before enabling checkout.'); }
      const pending = journal?.pending;
      if (pending && (pending.plannedSku === request.sku || pending.product?.variantId === request.variantId || pending.before?.variantId === request.variantId ||
        (validBarcode(pending.request?.barcode) && barcodeKey(pending.request.barcode) === barcodeKey(request.barcode)))) {
        fail('CHECKOUT_RECEIVING_PENDING', 'Finish the original pending stock receipt for this package before making it available at checkout. Do not receive it a second time.');
      }
    }
    const data = await this.graphql(`query ReceivingCheckoutPublications {
      publications(first: 250, catalogType: APP) { nodes { id name catalog { title } } pageInfo { hasNextPage } }
    }`);
    const publications = data.publications;
    const matches = publications?.nodes?.filter((publication: Json) => publication.name === 'Point of Sale' || publication.catalog?.title === 'Point of Sale') || [];
    if (publications?.pageInfo?.hasNextPage !== false || matches.length !== 1) fail('CHECKOUT_PUBLICATION_REQUIRED', 'The Point of Sale sales channel could not be identified uniquely. Review Shopify sales channels before continuing.');
    return gid(matches[0].id, 'Publication');
  }

  private async read(request: CheckoutInput, pos: string): Promise<Current> {
    const data = await this.graphql(`query ReceivingCheckoutVariant($id: ID!, $pos: ID!, $key: String!) {
      productVariant(id: $id) { id sku barcode title price pos: publishedOnPublication(publicationId: $pos)
        inventoryItem { id tracked }
        unit: metafield(namespace: "${RECEIVING.namespace}", key: "${RECEIVING.unitKey}") { value }
        game: metafield(namespace: "${RECEIVING.namespace}", key: "${RECEIVING.gameKey}") { value }
        barcodeId: metafield(namespace: "${RECEIVING.namespace}", key: "${RECEIVING.barcodeIdKey}") { value }
        checkoutPrice: metafield(namespace: "${RECEIVING.namespace}", key: $key) { value compareDigest }
        activeCheckoutPrice: metafield(namespace: "${RECEIVING.namespace}", key: "checkout_price_attempt") { value compareDigest }
        product { id title status productType pos: publishedOnPublication(publicationId: $pos)
          catalogId: metafield(namespace: "${RECEIVING.namespace}", key: "${RECEIVING.catalogIdKey}") { value }
          variants(first: 2) { nodes { id } pageInfo { hasNextPage } } ${memberships}
        }
      }
    }`, {id: request.variantId, pos, key: `checkout_price_${request.requestId}`});
    const node = data.productVariant;
    const parent = node?.product;
    if (!node || node.id !== request.variantId || parent?.id !== request.productId || node.sku !== request.sku ||
      !validBarcode(node.barcode) || barcodeKey(node.barcode) !== barcodeKey(request.barcode) || !node.inventoryItem?.id) {
      fail('CHECKOUT_IDENTITY_CHANGED', 'The selected Shopify product, SKU, or package barcode changed. Rescan and review the original sealed product.');
    }
    if (parent.status === 'ARCHIVED') fail('CHECKOUT_ARCHIVED', 'This product is archived. Review it in Shopify Admin before making it available at checkout.');
    if (!['ACTIVE', 'DRAFT'].includes(parent.status)) fail('CHECKOUT_STATUS_REVIEW', 'Review this product’s Shopify status before making it available at checkout.');
    if (!node.inventoryItem.tracked || !node.unit?.value || !node.game?.value || node.barcodeId?.value !== barcodeKey(request.barcode)) {
      fail('CHECKOUT_SEALED_REVIEW', 'This variant is not registered as tracked sealed stock by this receiver. Review its package barcode and receiving details in Shopify.');
    }
    const siblings = parent.variants;
    const singleVariant = siblings?.pageInfo?.hasNextPage === false && siblings.nodes?.length === 1 && siblings.nodes[0].id === request.variantId;
    if (parent.status === 'DRAFT') {
      const catalogId = parent.catalogId?.value || '';
      const source = /^scrydex:(pokemon|onepiece|riftbound):[a-zA-Z0-9_-]+$/.exec(catalogId);
      const sourceGame = source ? RECEIVING_CATALOG_GAMES[source[1] as keyof typeof RECEIVING_CATALOG_GAMES] : null;
      if (!singleVariant || !/^DEFY-S-\d{6}$/.test(request.sku) || !(catalogId === barcodeKey(request.barcode) ||
        (sourceGame && sourceGame === node.game.value && parent.productType === `${sourceGame} Sealed`))) {
        fail('CHECKOUT_DRAFT_REVIEW', 'Only a single-variant sealed draft created by this receiver can be activated here. Review this product and its other variants in Shopify Admin.');
      }
      // A variant can have opt-out default memberships on other channels while
      // remaining invisible because its parent is absent from those channels.
      for (const alias of Object.keys(channelTypes)) {
        const channels = parent[alias];
        if (channels?.pageInfo?.hasNextPage !== false || !Array.isArray(channels.nodes) || channels.nodes.length > 100 || channels.nodes.some((entry: Json) => entry.publication?.id !== pos)) {
          fail('CHECKOUT_CHANNEL_REVIEW', 'This draft has other or unverified sales-channel memberships. Review them in Shopify Admin before activating it.');
        }
      }
    } else if (!parent.pos && !singleVariant) {
      fail('CHECKOUT_VARIANTS_REVIEW', 'Publishing this product could expose other variants at checkout. Review its Point of Sale availability in Shopify Admin first.');
    }
    const price = money(node.price, 'Store price');
    return {node, parent, marker: node.checkoutPrice || null, activeMarker: node.activeCheckoutPrice || null, product: {sku: node.sku, barcode: node.barcode,
      name: node.title && node.title !== 'Default Title' ? `${parent.title} — ${node.title}` : parent.title,
      game: node.game.value, unit: node.unit.value, variantId: node.id, productId: parent.id, inventoryItemId: node.inventoryItem.id,
      barcodeNeedsReview: false, tracked: true, status: parent.status, catalogId: parent.catalogId?.value || '', barcodeId: node.barcodeId.value, price}};
  }

  private async uniqueBarcode(request: CheckoutInput): Promise<void> {
    const query = barcodeAliases(request.barcode).map(barcode => `barcode:"${barcode}"`).join(' OR ');
    const data = await this.graphql(`query ReceivingCheckoutBarcodes($query: String!) {
      productVariants(first: 100, query: $query) { nodes { id barcode } pageInfo { hasNextPage } }
    }`, {query});
    const result = data.productVariants;
    if (result?.pageInfo?.hasNextPage !== false || !Array.isArray(result.nodes)) {
      fail('CHECKOUT_BARCODE_REVIEW', 'The package barcode could not be checked completely. Review duplicate barcodes in Shopify Admin.');
    }
    // The pinned API returns the primary barcode only. A second search result
    // may match an additional barcode that this API cannot expose; never ignore it.
    const match = result.nodes[0];
    if (result.nodes.length !== 1 || match?.id !== request.variantId || !validBarcode(match.barcode) || barcodeKey(match.barcode) !== barcodeKey(request.barcode)) {
      fail('CHECKOUT_BARCODE_CONFLICT', 'This package barcode is missing or belongs to more than one Shopify variant. Resolve it in Shopify Admin before checkout.');
    }
  }

  private attempt(current: Current, request: CheckoutInput): PriceAttempt | null {
    if (!current.marker) return null;
    let saved: PriceAttempt;
    try { saved = JSON.parse(current.marker.value); } catch { fail('CHECKOUT_PRICE_REVIEW', 'The saved checkout price request needs owner review. Keep its original request ID.'); }
    if (!saved || saved.version !== 1 || saved.fingerprint !== stableJson(request) || saved.fingerprint !== stableJson(saved.request) ||
      !['pending', 'applied'].includes(saved.phase) || typeof saved.before !== 'string') fail('CHECKOUT_PRICE_CONFLICT', 'This checkout request ID already belongs to different or damaged price details. Keep its original request for review.');
    return saved;
  }

  private activeAttempt(current: Current): PriceAttempt | null {
    if (!current.activeMarker) return null;
    let active: PriceAttempt;
    try { active = JSON.parse(current.activeMarker.value); } catch { fail('CHECKOUT_PRICE_REVIEW', 'The previous checkout price request needs owner review before a new checkout action.'); }
    if (!active || active.version !== 1 || !active.request || active.fingerprint !== stableJson(normalize(active.request)) || !['pending', 'applied'].includes(active.phase) || active.request.storePrice === undefined) {
      fail('CHECKOUT_PRICE_REVIEW', 'The previous checkout price request is incomplete. Ask the owner to review it before continuing.');
    }
    return active;
  }

  private checkActiveAttempt(current: Current, request: CheckoutInput): void {
    const active = this.activeAttempt(current);
    if (!active) return;
    if (active.phase === 'pending' && active.request.requestId !== request.requestId) {
      fail('CHECKOUT_PRICE_PENDING', `Checkout price request ${active.request.requestId} is still unconfirmed. Review its store price of ${active.request.storePrice} in Shopify Admin, then retry checkout. No price was overwritten.`);
    }
  }

  private async saveAttempt(request: CheckoutInput, attempt: PriceAttempt, current: Current): Promise<boolean> {
    const saved = this.attempt(current, request);
    // A peer may already have confirmed this request and a newer request may
    // own the active marker. Never write the old marker over that newer owner.
    if (saved?.phase === 'applied' && attempt.phase === 'applied') return true;
    this.checkActiveAttempt(current, request);
    if (saved && this.activeAttempt(current)?.fingerprint !== saved.fingerprint) fail('CHECKOUT_PRICE_REVIEW', 'The checkout price attempt no longer owns its saved confirmation. Review the current request before continuing.');
    const data = await this.graphql(`mutation ReceivingCheckoutPriceCAS($metafields: [MetafieldsSetInput!]!) {
      metafieldsSet(metafields: $metafields) { metafields { id compareDigest } userErrors { code field message } }
    }`, {metafields: [[`checkout_price_${request.requestId}`, current.marker?.compareDigest || null], ['checkout_price_attempt', current.activeMarker?.compareDigest || null]]
      .map(([key, compareDigest]) => ({ownerId: request.variantId, namespace: RECEIVING.namespace, key,
        type: 'json', value: stableJson(attempt), compareDigest}))});
    const errors = data.metafieldsSet?.userErrors || [];
    if (errors.length && errors.every((error: Json) => ['INVALID_COMPARE_DIGEST', 'STALE_OBJECT', 'TAKEN'].includes(error.code))) return false;
    check(data.metafieldsSet, 'Saving the checkout price request');
    if (!data.metafieldsSet.metafields?.length) fail('CHECKOUT_UNCERTAIN', 'The checkout price request save could not be confirmed. Retry the same request.', true);
    return true;
  }

  async prepare(input: CheckoutInput): Promise<{ok: true; product: Product; publicationId: string}> {
    const request = normalize(input);
    let writesStarted = false;
    try {
      const pos = await this.publication(request);
      let current = await this.read(request, pos);
      // Durable work from an earlier call still makes this an uncertain retry,
      // even when this invocation has not sent a mutation yet.
      if (current.marker) { writesStarted = true; this.attempt(current, request); }
      await this.uniqueBarcode(request);
      const active = this.activeAttempt(current);
      if (active?.phase === 'pending') writesStarted = true;
      if (active?.phase === 'pending' && active.request.requestId !== request.requestId) {
        const sameIdentity = active.request.productId === request.productId && active.request.variantId === request.variantId && active.request.sku === request.sku && barcodeKey(active.request.barcode) === barcodeKey(request.barcode);
        if (!sameIdentity || current.product.price !== active.request.storePrice || (request.storePrice !== undefined && request.storePrice !== active.request.storePrice)) this.checkActiveAttempt(current, request);
        // The modal may have closed after Shopify saved the price. A new action
        // may confirm the old exact price read-only; it must never resend it.
        const original = await this.read(active.request, pos);
        const originalActive = this.activeAttempt(original);
        if (originalActive?.fingerprint !== active.fingerprint) fail('CHECKOUT_PRICE_PENDING', 'Another checkout price request started during recovery. Review the current request before continuing.');
        if (original.product.price !== active.request.storePrice || !this.attempt(original, active.request)) this.checkActiveAttempt(current, request);
        writesStarted = true;
        if (!await this.saveAttempt(active.request, {...active, phase: 'applied'}, original)) {
          current = await this.read(request, pos);
          this.checkActiveAttempt(current, request);
        }
        current = await this.read(request, pos);
      }
      this.checkActiveAttempt(current, request);
      if (request.storePrice === undefined && Number(current.product.price) <= 0) fail('CHECKOUT_PRICE_REQUIRED', 'Enter a positive store price before making this product available at checkout. Unit cost is not a selling price.');
      if (request.storePrice !== undefined) {
        let attempt = this.attempt(current, request);
        let mayWrite = false;
        if (!attempt) {
          attempt = {version: 1, fingerprint: stableJson(request), request, before: current.product.price!, phase: 'pending'};
          writesStarted = true;
          mayWrite = await this.saveAttempt(request, attempt, current);
          current = await this.read(request, pos);
          this.checkActiveAttempt(current, request);
          const saved = this.attempt(current, request);
          if (!saved) fail('CHECKOUT_UNCERTAIN', 'The checkout price request is not yet visible. Retry the same request.', true);
          attempt = saved;
        }
        if (current.product.price !== request.storePrice) {
          if (!mayWrite || attempt.phase !== 'pending') fail('CHECKOUT_PRICE_REVIEW', 'An earlier checkout price attempt may have completed, but Shopify now shows a different price. Review the price in Shopify and retry this same request; the receiver will not overwrite it again.');
          if (current.product.price !== attempt.before) fail('CHECKOUT_PRICE_REVIEW', 'The Shopify price changed while this checkout request was being saved. Review it before continuing.');
          writesStarted = true;
          const updated = await this.graphql(`mutation ReceivingCheckoutPrice($productId: ID!, $variants: [ProductVariantsBulkInput!]!) {
            productVariantsBulkUpdate(productId: $productId, variants: $variants) { productVariants { id price } userErrors { code field message } }
          }`, {productId: request.productId, variants: [{id: request.variantId, price: request.storePrice}]});
          check(updated.productVariantsBulkUpdate, 'Setting the checkout store price');
          current = await this.read(request, pos);
          if (current.product.price !== request.storePrice) fail('CHECKOUT_PRICE_REVIEW', 'Shopify did not confirm the requested store price. Review the current price and retry this same request; it will not be written again.');
        }
        if (attempt.phase !== 'applied') {
          writesStarted = true;
          if (!await this.saveAttempt(request, {...attempt, phase: 'applied'}, current)) {
            current = await this.read(request, pos);
            this.checkActiveAttempt(current, request);
            if (this.attempt(current, request)?.phase !== 'applied') fail('CHECKOUT_UNCERTAIN', 'Another device changed the checkout price confirmation. Retry this same request.', true);
          }
        }
      }
      // Recheck immediately before availability writes; nothing here changes stock.
      current = await this.read(request, pos);
      this.checkActiveAttempt(current, request);
      await this.uniqueBarcode(request);
      this.positivePrice(current, request);
      if (current.parent.status !== 'ACTIVE') {
        writesStarted = true;
        const activated = await this.graphql(`mutation ReceivingCheckoutActivate($product: ProductUpdateInput!) {
          productUpdate(product: $product) { product { id status } userErrors { code field message } }
        }`, {product: {id: request.productId, status: 'ACTIVE'}});
        check(activated.productUpdate, 'Activating the sealed product');
        current = await this.read(request, pos);
        this.positivePrice(current, request);
        if (current.parent.status !== 'ACTIVE') fail('CHECKOUT_UNCERTAIN', 'Shopify has not confirmed the active product. Retry the same request.', true);
      }
      for (const variant of [false, true]) {
        if (variant ? current.node.pos : current.parent.pos) continue;
        writesStarted = true;
        const published = await this.graphql(`mutation ReceivingCheckoutPublish($id: ID!, $input: [PublicationInput!]!) {
          publishablePublish(id: $id, input: $input) { userErrors { field message } }
        }`, {id: variant ? request.variantId : request.productId, input: [{publicationId: pos}]});
        check(published.publishablePublish, 'Making the sealed product available in Point of Sale');
        current = await this.read(request, pos);
        this.positivePrice(current, request);
      }
      current = await this.read(request, pos);
      await this.uniqueBarcode(request);
      this.positivePrice(current, request);
      if (current.parent.status !== 'ACTIVE' || current.parent.pos !== true || current.node.pos !== true) fail('CHECKOUT_UNCERTAIN', 'Shopify has not confirmed both the product and its variant in Point of Sale. Retry the same checkout request.', true);
      return {ok: true, product: current.product, publicationId: pos};
    } catch (error) {
      if (error instanceof ReceivingError) {
        if (writesStarted) error.committedPossible = true;
        throw error;
      }
      throw new ReceivingError('CHECKOUT_UNCERTAIN', 'Shopify checkout availability could not be confirmed. Retry the same request; do not receive this stock again.', true, writesStarted);
    }
  }

  private positivePrice(current: Current, request: CheckoutInput) {
    if (Number(current.product.price) <= 0) fail('CHECKOUT_PRICE_REQUIRED', 'Shopify must show a positive store price before this product is ready at checkout.');
    if (request.storePrice !== undefined && current.product.price !== request.storePrice) fail('CHECKOUT_PRICE_REVIEW', 'The Shopify store price changed before checkout availability was confirmed. Review it without receiving stock again.');
  }
}

export async function makeAvailableAtCheckout(input: CheckoutInput): Promise<CheckoutResult> {
  try { return await new CheckoutService().prepare(input); }
  catch (error) {
    if (error instanceof ReceivingError) return {ok: false, error: {code: error.code, message: error.message, retryable: error.retryable, committedPossible: error.committedPossible}};
    return {ok: false, error: {code: 'CHECKOUT_UNCERTAIN', message: 'Checkout availability could not be confirmed. Retry the same request.', retryable: true, committedPossible: true}};
  }
}
