import {ShopifyReceivingAdapter} from './shopify-receiving-adapter.ts';
import {barcodeKey, gid, isoDate, money, optionalStorePrice, quantity, ReceivingError, scanBarcode, stableJson, text, validBarcode, validation} from './receiving-validation.ts';
import {normalizeCatalogReference, normalizeReceiptCatalog, RECEIVING_CATALOG_GAMES, type CatalogReference, type ReceiptCatalog} from './receiving-catalog.ts';

export {ReceivingError} from './receiving-validation.ts';
export const RECEIVING = Object.freeze({
  namespace: '$app:receiving', stateKey: 'state', clockKey: 'clock', catalogIdKey: 'catalog_id', barcodeIdKey: 'barcode_id', unitKey: 'unit', gameKey: 'game',
  intentType: '$app:receiving_intent', appliedType: '$app:receiving_applied',
  // Stop conservatively before the documented 24-hour idempotency retention.
  retryWindowMs: 23 * 60 * 60 * 1000, skuPrefix: 'DEFY-S-', apiVersion: '2026-07',
});

export type ReceiptInput = {
  requestId: string; barcode: string; sku?: string; name: string; game: string; unit: string;
  quantity: string | number; unitCost: string; storePrice?: string; supplier: string; notes: string; receivedDate: string;
  replaceInvalidBarcode?: boolean; locationId?: string | number; locationName?: string;
  catalog?: ReceiptCatalog;
};
export type Request = Omit<ReceiptInput, 'quantity' | 'sku' | 'replaceInvalidBarcode' | 'locationId' | 'locationName'> & {
  quantity: number; sku: string; replaceInvalidBarcode: boolean; locationId: string;
};
export type Product = {
  sku: string; barcode: string; name: string; game: string; unit: string;
  variantId: string; productId: string; inventoryItemId: string;
  barcodeNeedsReview: boolean; tracked: boolean; status: string; catalogId?: string; barcodeId?: string; price?: string;
};
export type Adjustment = {id: string; createdAt: string; referenceDocumentUri: string};
export type Receipt = Request & {
  productId: string; variantId: string; inventoryItemId: string; sku: string;
  recordedAt: string; appliedAt: string; adjustmentGroupId: string; locationName: string;
  currencyCode: string; createdProduct: boolean; staged: boolean;
};
export type Plan = {
  version: 1; request: Request; fingerprint: string; startedAt: string;
  plannedSku: string; createdProduct: boolean; before: Product | null;
  locationName: string; currencyCode: string;
  phase: 'planned' | 'product_ready' | 'price_pending' | 'price_applied' | 'inventory_pending' | 'inventory_applied';
  product?: Product; inventoryStartedAt?: string; adjustment?: Adjustment;
};
export type JournalState = {version: 1; nextSequence: number; pending: Plan | null};
export type StateSnapshot = {shopId: string; currencyCode: string; digest: string | null; state: JournalState | null};
export type Applied = {version: 1; fingerprint: string; product: Product; receipt: Receipt};
export type Success = {ok: true; duplicate: boolean; createdProduct: boolean; staged: boolean; product: Product; receipt: Receipt};
export type Failure = {ok: false; error: {code: string; message: string; retryable: boolean; committedPossible: boolean; definitelyUncommitted?: boolean}; pendingRequest?: Request};

export interface ReceivingAdapter {
  serverNow(): Promise<number>;
  readState(): Promise<StateSnapshot>;
  compareAndSet(snapshot: StateSnapshot, state: JournalState): Promise<boolean>;
  readRecord(kind: 'intent' | 'applied', requestId: string): Promise<Plan | Applied | null>;
  createRecord(kind: 'intent' | 'applied', requestId: string, value: Plan | Applied): Promise<void>;
  location(id: string): Promise<{id: string; name: string; active: boolean}>;
  findByBarcode(barcode: string): Promise<Product[]>;
  findBySku(sku: string): Promise<Product[]>;
  findByCatalog(catalog: CatalogReference): Promise<Product | null>;
  search(query: string): Promise<{products: Product[]; hasMore: boolean}>;
  resolveProduct(plan: Plan): Promise<Product>;
  applyStorePrice(product: Product, plan: Plan): Promise<Product>;
  confirmStorePrice(product: Product, plan: Plan): Promise<Product>;
  ensureActive(product: Product, plan: Plan): Promise<void>;
  adjust(product: Product, plan: Plan): Promise<Adjustment>;
}

function conflict(message: string, code = 'MANUAL_REVIEW'): never {
  throw new ReceivingError(code, message, false, true);
}

export function normalizeRequest(input: ReceiptInput, locationId: unknown): Request {
  if (!input || typeof input !== 'object') validation('A receipt form is required.');
  const id = text(input.requestId, 'Request ID', 100, true);
  // Lowercase avoids Shopify metaobject handle case normalization collisions.
  if (!/^[a-z0-9][a-z0-9-]{15,99}$/.test(id)) validation('Use the unique request ID generated by this receiver.');
  if (input.replaceInvalidBarcode !== undefined && typeof input.replaceInvalidBarcode !== 'boolean') validation('Barcode replacement confirmation must be true or false.');
  const name = text(input.name, 'Product name', 300, true);
  const game = text(input.game, 'Game', 80, true);
  const catalog = input.catalog === undefined ? undefined : normalizeReceiptCatalog(input.catalog, name, game);
  const storePrice = optionalStorePrice(input.storePrice);
  return {
    requestId: id, barcode: scanBarcode(input.barcode), sku: text(input.sku, 'SKU', 80),
    name, game: catalog ? RECEIVING_CATALOG_GAMES[catalog.game] : game,
    unit: text(input.unit, 'Package unit', 80, true), quantity: quantity(input.quantity), unitCost: money(input.unitCost),
    supplier: text(input.supplier, 'Supplier', 300), notes: text(input.notes, 'Notes', 1500),
    receivedDate: isoDate(input.receivedDate), replaceInvalidBarcode: input.replaceInvalidBarcode === true,
    locationId: gid(input.locationId || locationId, 'Location'),
    // Do not add an undefined key: historical receipt fingerprints must stay exact.
    ...(catalog ? {catalog} : {}),
    ...(storePrice !== undefined ? {storePrice} : {}),
  };
}

export function assertState(snapshot: StateSnapshot): JournalState {
  const state = snapshot.state;
  if (!state) throw new ReceivingError('SETUP_REQUIRED', 'Receiving has not been initialized for this shop. Ask the owner to finish app setup.');
  if (state.version !== 1 || !Number.isSafeInteger(state.nextSequence) || state.nextSequence < 1 || !('pending' in state)) conflict('Receiving state is damaged. The SKU counter was not reset.');
  if (state.pending) {
    const p = state.pending;
    if (p.version !== 1 || !p.request || p.fingerprint !== stableJson(p.request) || !p.plannedSku || !Number.isFinite(Date.parse(p.startedAt)) ||
      !['planned', 'product_ready', 'price_pending', 'price_applied', 'inventory_pending', 'inventory_applied'].includes(p.phase)) conflict('The pending receipt needs owner review. Its original request ID is preserved.');
    if (p.phase !== 'planned' && !p.product) conflict('The pending receipt is missing its Shopify identity.');
    if ((p.phase === 'price_pending' || p.phase === 'price_applied') &&
      (typeof p.request.storePrice !== 'string' || !/^\d+\.\d{2}$/.test(p.request.storePrice) || typeof p.product?.price !== 'string')) conflict('The pending store price is incomplete. Keep the original receipt for owner review.');
    if (p.phase === 'price_applied' && p.product?.price !== p.request.storePrice) conflict('The pending receipt is missing its store price confirmation.');
    if ((p.phase === 'inventory_pending' || p.phase === 'inventory_applied') && !Number.isFinite(Date.parse(p.inventoryStartedAt || ''))) conflict('The pending inventory attempt is missing its original timestamp.');
    if (p.phase === 'inventory_applied' && !p.adjustment?.id) conflict('The pending receipt is missing its inventory confirmation.');
  }
  return state;
}

function onlyProduct(products: Product[], description: string): Product | null {
  if (products.length > 1) throw new ReceivingError('AMBIGUOUS_CATALOG', `${description} matches more than one Shopify variant. Resolve duplicates before receiving.`);
  return products[0] || null;
}

export function validateExisting(product: Product, request: Request): void {
  if (!product.sku) validation('This Shopify variant has no SKU. Assign its permanent SKU before receiving.');
  if (product.status === 'ARCHIVED') validation('This product is archived. Ask the owner to review it before receiving.');
  if (!product.tracked) validation('Inventory tracking is disabled for this variant. Enable it before receiving.');
  if (product.name !== request.name || (product.game && product.game !== request.game)) validation('Product identity changed. Look up the product again.');
  if (product.unit && product.unit !== request.unit) validation('This SKU uses a different package unit. Packs, boxes and cases need separate SKUs.');
  if (product.barcode && barcodeKey(product.barcode) !== barcodeKey(request.barcode) && (validBarcode(product.barcode) || !request.replaceInvalidBarcode)) {
    validation('This SKU has a different barcode. Replace an invalid historical barcode only after explicit confirmation.');
  }
}

function completed(record: Applied, fingerprint: string, duplicate: boolean): Success {
  if (record.version !== 1 || record.fingerprint !== fingerprint) conflict('This request ID already belongs to different receipt details. Keep the original ID for review.', 'IDEMPOTENCY_CONFLICT');
  if (!record.receipt?.adjustmentGroupId || !record.product?.variantId) conflict('The recorded receipt is incomplete. Do not receive it again.');
  return {ok: true, duplicate, createdProduct: record.receipt.createdProduct, staged: record.receipt.staged, product: record.product, receipt: record.receipt};
}

/**
 * One shop-wide nonexpiring transaction, advanced with compareDigest CAS.
 * No inventory delta is sent before its exact request + start time are durable.
 * A retry may finish another device's same transaction; it never steals a lock.
 */
export class ReceivingService {
  readonly adapter: ReceivingAdapter;
  constructor(adapter: ReceivingAdapter) { this.adapter = adapter; }

  async pending(): Promise<Request | null> {
    const state = assertState(await this.adapter.readState());
    return state.pending ? {...state.pending.request} : null;
  }

  async receive(request: Request): Promise<Success> {
    const fingerprint = stableJson(request);
    let owned = false;
    let duplicate = false;
    let acquiredNew = false;
    // A price mutation has no Shopify idempotency key. Only the device that
    // confirms this CAS may send it; every subsequent attempt is read-only.
    let priceWriteAuthorized = false;
    try {
      for (let attempt = 0; attempt < 40; attempt++) {
        const record = await this.adapter.readRecord('applied', request.requestId) as Applied | null;
        const snapshot = await this.adapter.readState();
        const state = assertState(snapshot);
        if (record) {
          const result = completed(record, fingerprint, true);
          // Clearing a matching finished transaction is safe after durable confirmation.
          if (state.pending?.request.requestId === request.requestId) {
            if (state.pending.fingerprint !== fingerprint) conflict('The saved receipt and pending transaction disagree.');
            if (!await this.adapter.compareAndSet(snapshot, {...state, pending: null})) continue;
          }
          return result;
        }
        let plan = state.pending;
        if (plan) {
          if (plan.request.requestId !== request.requestId) {
            const finished = await this.adapter.readRecord('applied', request.requestId) as Applied | null;
            if (finished) return completed(finished, fingerprint, true);
            if (await this.adapter.readRecord('intent', request.requestId)) conflict('This receipt has an intent but another transaction replaced its pending state. Ask the owner to review it.');
            const busy = new ReceivingError('RECEIVING_BUSY', `This delivery was not started. Receipt ${plan.request.requestId} must finish first; then enter this delivery again.`, true, false, plan.request);
            busy.definitelyUncommitted = true;
            throw busy;
          }
          owned = true;
          if (plan.fingerprint !== fingerprint) conflict('This request ID belongs to different pending receipt details. Restore the original receipt.', 'IDEMPOTENCY_CONFLICT');
          duplicate = !acquiredNew;
        } else {
          // A durable intent without its pending state/applied marker indicates tampering.
          if (await this.adapter.readRecord('intent', request.requestId)) {
            // Another device can finish between our applied-record and state reads.
            const finished = await this.adapter.readRecord('applied', request.requestId) as Applied | null;
            if (finished) return completed(finished, fingerprint, true);
            conflict('This receipt has an intent but its transaction state is missing. Ask the owner to reconcile it.');
          }
          const location = await this.adapter.location(request.locationId);
          if (!location.active) validation('This receiving location is inactive. Select the correct POS location.');
          const byBarcode = onlyProduct(await this.adapter.findByBarcode(request.barcode), 'This barcode');
          const bySku = request.sku ? onlyProduct(await this.adapter.findBySku(request.sku), 'This SKU') : null;
          const byCatalog = request.catalog ? await this.adapter.findByCatalog(request.catalog) : null;
          if (request.sku && !bySku) validation('That existing SKU was not found. Search and select the Shopify product again.');
          if (byBarcode && bySku && byBarcode.variantId !== bySku.variantId) validation('This barcode belongs to another Shopify SKU.');
          if (byCatalog && [byBarcode, bySku].some(product => product && product.variantId !== byCatalog.variantId)) validation('This catalog product is already registered to another Shopify SKU. Select its existing product.');
          if (request.catalog && !byCatalog && (byBarcode || bySku)) validation('This barcode or SKU now belongs to an existing Shopify item. Select that item to preserve its permanent identity.');
          const before = byCatalog || bySku || byBarcode;
          if (before) validateExisting(before, request);
          let nextSequence = state.nextSequence;
          let plannedSku = before?.sku || '';
          if (!before) {
            // Even after initialization, never take a SKU assigned outside this app.
            for (let n = 0; n < 100; n++) {
              if (nextSequence > 999999) throw new ReceivingError('SEQUENCE_EXHAUSTED', 'The six-digit sealed SKU sequence needs owner review.');
              plannedSku = `${RECEIVING.skuPrefix}${String(nextSequence++).padStart(6, '0')}`;
              if (!(await this.adapter.findBySku(plannedSku)).length) break;
              plannedSku = '';
            }
            if (!plannedSku) throw new ReceivingError('SEQUENCE_CONFLICT', 'Too many reserved SKUs were encountered. Ask the owner to advance the sequence safely.');
          }
          plan = {version: 1, request, fingerprint, startedAt: new Date(await this.adapter.serverNow()).toISOString(), plannedSku,
            createdProduct: !before, before, locationName: location.name, currencyCode: snapshot.currencyCode, phase: 'planned'};
          // Counter reservation and immutable receipt plan are the SAME atomic write.
          owned = true; // A transport failure here may have committed the CAS.
          if (!await this.adapter.compareAndSet(snapshot, {...state, nextSequence, pending: plan})) { owned = false; continue; }
          acquiredNew = true;
          continue;
        }

        if (plan.phase === 'planned') {
          await this.adapter.createRecord('intent', request.requestId, plan);
          const product = await this.adapter.resolveProduct(plan);
          if (product.sku !== plan.plannedSku || barcodeKey(product.barcode) !== barcodeKey(request.barcode) || product.unit !== request.unit) conflict('The Shopify product no longer matches the reserved receipt identity.');
          if (!await this.adapter.compareAndSet(snapshot, {...state, pending: {...plan, product, phase: 'product_ready'}})) continue;
          continue;
        }
        if (plan.phase === 'product_ready' && request.storePrice !== undefined) {
          if (plan.product!.price === undefined) conflict('Shopify did not return the current store price. Keep this receipt for owner review.', 'STORE_PRICE_UNAVAILABLE');
          if (!await this.adapter.compareAndSet(snapshot, {...state, pending: {...plan, phase: 'price_pending'}})) continue;
          priceWriteAuthorized = true;
          continue;
        }
        if (plan.phase === 'price_pending') {
          const mayWrite = priceWriteAuthorized;
          priceWriteAuthorized = false;
          const product = mayWrite ? await this.adapter.applyStorePrice(plan.product!, plan) : await this.adapter.confirmStorePrice(plan.product!, plan);
          if (product.price !== request.storePrice) conflict('Shopify did not confirm the entered store price. Keep this receipt pending.', 'STORE_PRICE_UNCERTAIN');
          if (!await this.adapter.compareAndSet(snapshot, {...state, pending: {...plan, product, phase: 'price_applied'}})) continue;
          continue;
        }
        if (plan.phase === 'product_ready' || plan.phase === 'price_applied') {
          await this.adapter.ensureActive(plan.product!, plan);
          // Timestamp is persisted before the first possible stock adjustment.
          const next = {...plan, phase: 'inventory_pending' as const, inventoryStartedAt: new Date(await this.adapter.serverNow()).toISOString()};
          if (!await this.adapter.compareAndSet(snapshot, {...state, pending: next})) continue;
          continue;
        }
        if (plan.phase === 'inventory_pending') {
          const age = await this.adapter.serverNow() - Date.parse(plan.inventoryStartedAt!);
          if (age < -5 * 60 * 1000 || age >= RECEIVING.retryWindowMs) conflict('The inventory result is uncertain and its safe retry window has ended. Ask the owner to reconcile Shopify inventory history using this request ID. Do not submit a new receipt.', 'RETRY_WINDOW_EXPIRED');
          const adjustment = await this.adapter.adjust(plan.product!, plan);
          if (!adjustment?.id) conflict('Shopify did not provide an inventory confirmation. Keep this receipt pending.');
          if (!await this.adapter.compareAndSet(snapshot, {...state, pending: {...plan, phase: 'inventory_applied', adjustment}})) continue;
          continue;
        }
        const product = plan.product!;
        const applied: Applied = {version: 1, fingerprint, product, receipt: {
          ...request, sku: product.sku, name: product.name, game: product.game || request.game, unit: product.unit,
          productId: product.productId, variantId: product.variantId, inventoryItemId: product.inventoryItemId,
          recordedAt: plan.startedAt, appliedAt: plan.adjustment!.createdAt, adjustmentGroupId: plan.adjustment!.id,
          locationName: plan.locationName, currencyCode: plan.currencyCode, createdProduct: plan.createdProduct,
          staged: product.status !== 'ACTIVE',
        }};
        await this.adapter.createRecord('applied', request.requestId, applied);
        if (!await this.adapter.compareAndSet(snapshot, {...state, pending: null})) continue;
        return completed(applied, fingerprint, duplicate);
      }
      throw new ReceivingError('RETRY_LATER', 'Receiving changed on another device. Retry this same receipt.', true, true);
    } catch (error) {
      if (error instanceof ReceivingError) {
        // Validation after acquiring a durable plan must NEVER release the request ID.
        if (owned && !error.committedPossible) throw new ReceivingError(error.code === 'VALIDATION' ? 'MANUAL_REVIEW' : error.code, error.message, error.retryable, true);
        throw error;
      }
      throw new ReceivingError('CONNECTION_UNCERTAIN', 'The result could not be confirmed. Keep these details and retry the same receipt after checking the connection.', true, owned);
    }
  }
}

type NativeStorage = {get(key: string): Promise<unknown>; set(key: string, value: unknown): Promise<void>; delete(key: string): Promise<unknown>};
type PosRuntime = {storage: NativeStorage; session: {currentSession: {locationId: number; shopId: number}}};
function runtime(): PosRuntime {
  const value = (globalThis as unknown as {shopify?: PosRuntime}).shopify;
  if (!value?.storage || !value.session?.currentSession) throw new ReceivingError('POS_REQUIRED', 'Open receiving from Shopify POS on the iPad.');
  return value;
}
function storageKey(pos: PosRuntime): string { return `defy-receiving-pending-v1-${pos.session.currentSession.shopId}`; }
function failure(error: unknown): Failure {
  if (error instanceof ReceivingError) return {ok: false, error: {code: error.code, message: error.message, retryable: error.retryable, committedPossible: error.committedPossible,
    definitelyUncommitted: error.definitelyUncommitted}, ...(error.definitelyUncommitted && error.pending ? {pendingRequest: error.pending as Request} : {})};
  return {ok: false, error: {code: 'CONNECTION_UNCERTAIN', message: 'Could not confirm the result. Keep the same receipt and retry after checking the connection.', retryable: true, committedPossible: true}};
}
const production = () => new ReceivingService(new ShopifyReceivingAdapter());

export async function findProduct(input: {barcode: string}) {
  try {
    const barcode = scanBarcode(input?.barcode);
    const product = onlyProduct(await production().adapter.findByBarcode(barcode), 'This barcode');
    return {ok: true as const, found: Boolean(product), barcode, product};
  } catch (error) { return failure(error); }
}

export async function searchProducts(input: {query: string}) {
  try {
    const query = text(input?.query, 'Search', 300);
    const result = query ? await production().adapter.search(query) : {products: [], hasMore: false};
    return {ok: true as const, ...result};
  } catch (error) { return failure(error); }
}

export async function findCatalogProduct(input: CatalogReference) {
  try {
    const catalog = normalizeCatalogReference(input);
    const product = await production().adapter.findByCatalog(catalog);
    return {ok: true as const, found: Boolean(product), product};
  } catch (error) { return failure(error); }
}

export async function loadPendingReceipt() {
  try {
    const pos = runtime();
    let local = await pos.storage.get(storageKey(pos)) as Request | null;
    const service = production();
    const remote = await service.pending();
    if (local && remote && local.requestId !== remote.requestId) {
      const saved = await service.adapter.readRecord('applied', local.requestId) as Applied | null;
      if (saved) completed(saved, stableJson(local), true);
      else if (await service.adapter.readRecord('intent', local.requestId)) conflict('The local receipt has an intent but another transaction owns the journal. Ask the owner to review it.');
      // Local-only draft A never acquired the journal while durable B owns it.
      // Reopen must expose B instead of trapping this device on A forever.
      await pos.storage.delete(storageKey(pos));
      local = null;
    }
    const request = local || remote;
    const activeLocation = gid(pos.session.currentSession.locationId, 'Location');
    const location = await production().adapter.location(request?.locationId || activeLocation);
    if (!location.active) throw new ReceivingError('LOCATION_INVALID', 'The receiving location is inactive. Ask the owner to review it.');
    if (request) {
      normalizeRequest(request, request.locationId);
      if (!local) await pos.storage.set(storageKey(pos), request);
    }
    return {ok: true as const, request: request ? {...request, locationName: location.name} : null, locationName: location.name};
  } catch (error) { return failure(error); }
}

export async function saveReceipt(input: ReceiptInput): Promise<Success | Failure> {
  let pos: PosRuntime | undefined;
  let request: Request | undefined;
  let hadPending = false;
  try {
    pos = runtime();
    const key = storageKey(pos);
    let local = await pos.storage.get(key) as Request | null;
    if (local && local.requestId !== input?.requestId) {
      // A prior success whose local cleanup failed can be safely acknowledged here.
      const saved = await production().adapter.readRecord('applied', local.requestId) as Applied | null;
      if (!saved) throw new ReceivingError('LOCAL_PENDING', 'Finish the saved receipt before starting a new receipt.', true, true);
      completed(saved, stableJson(local), true);
      await pos.storage.delete(key);
      local = null;
    }
    hadPending = Boolean(local);
    request = normalizeRequest(input, local?.locationId || pos.session.currentSession.locationId);
    if (local && stableJson(local) !== stableJson(request)) conflict('The saved request ID must keep its original receipt details.', 'IDEMPOTENCY_CONFLICT');
    // Native persistence is required BEFORE the first network mutation.
    await pos.storage.set(key, request);
    if (stableJson(await pos.storage.get(key)) !== stableJson(request)) throw new ReceivingError('LOCAL_STORAGE_FAILED', 'The iPad could not preserve this receipt. No new Shopify operation was started.', true, Boolean(local));
    const result = await production().receive(request);
    // Shopify confirmation is durable even if local cleanup fails.
    try { await pos.storage.delete(key); } catch { /* Next open replays the completed ID. */ }
    return result;
  } catch (error) {
    if (hadPending && error instanceof ReceivingError && error.code === 'VALIDATION') {
      error = new ReceivingError('IDEMPOTENCY_CONFLICT', 'The pending receipt must keep its original valid details. Restore the saved receipt before retrying.', false, true);
    }
    const result = failure(error);
    if (result.error.definitelyUncommitted && result.pendingRequest && pos) {
      try {
        await pos.storage.delete(storageKey(pos));
        await pos.storage.set(storageKey(pos), result.pendingRequest);
      } catch {
        result.error.definitelyUncommitted = false;
        delete result.pendingRequest;
        result.error.message = 'Another receipt must finish first, but the iPad could not save its recovery details. Reopen receiving after checking the device.';
      }
    }
    if (result.error.code === 'VALIDATION' && !result.error.retryable && !result.error.committedPossible && pos && request) {
      try { await pos.storage.delete(storageKey(pos)); } catch { result.error.retryable = true; }
    }
    return result;
  }
}
